import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    tr: {
        // Common
        'close': 'Kapat',
        'nav.back': 'Geri',

        // Cookie Consent
        'cookie.text': 'Bu site, deneyiminizi iyileştirmek için çerezler kullanır. Devam ederek çerez politikamızı kabul etmiş olursunuz.',
        'cookie.accept': 'Kabul Et',

        // VideoLanding
        'landing.title': 'Lezzeti Keşfet',
        'landing.subtitle': "Ege'nin en özel lezzetleri ve eşsiz sunumları sizi bekliyor.",
        'landing.cta': 'Menüyü Görüntüle',
        'landing.brandName': 'Kozbeyli Konağı',
        'landing.brandSub': 'Taş Otel',
        'landing.switchLang': 'English',

        // CategoryGrid
        'menu.welcome': 'Hoş Geldiniz',
        'menu.restaurant': 'Kozbeyli Konağı',
        'menu.search': 'Ne yemek istersiniz?',
        'menu.categories': 'Kategoriler',
        'menu.poweredBy': 'Kozbeyli Konağı',

        // ProductModal
        'product.addToOrder': 'Siparişe Ekle',
        'product.addedToOrder': 'Siparişe eklendi!',
        'product.shared': 'Kopyalandı!',
        'product.share': 'Paylaş',
        'product.outOfStock': 'Tükendi',
        'product.notFound': 'Ürün bulunamadı.',
        'product.pairingTitle': 'Gurme Eşleşme',
        'product.suggestions': 'Öneriler',
        'product.why': 'Neden?',
        'product.notes': 'Açıklamalar',
        'product.category': 'Kategori',
        'product.explore': 'Keşfet',
        'product.showMore': 'Devamını Gör',
        'product.showLess': 'Daha Az',
        'product.info': 'Bilgi',

        // Review
        'review.title': 'Değerlendir',
        'review.rateExperience': 'Deneyiminizi puanlayın',
        'review.nameLabel': 'İsim (Opsiyonel)',
        'review.namePlaceholder': 'İsminiz...',
        'review.commentLabel': 'Yorumunuz',
        'review.commentPlaceholder': 'Görüşlerinizi yazın...',
        'review.submit': 'Gönder',
        'review.thankYou': 'Teşekkürler!',
        'review.thankYouMessage': 'Yorumunuz bizim için çok değerli.',
        'review.ratingRequired': 'Lütfen puan verin.',
        'review.error': 'Bir hata oluştu.',
        'review.rating5': 'Muhteşem!',
        'review.rating4': 'Çok İyi',
        'review.rating3': 'İdare Eder',
        'review.rating2': 'Kötü',
        'review.rating1': 'Çok Kötü',

        // AI Assistant
        'assistant.welcome': 'Merhaba! Ben Kozbeyli Konağı yapay zeka asistanıyım. Size menümüz hakkında nasıl yardımcı olabilirim?',
        'assistant.error': 'Üzgünüm, şu an yanıt veremiyorum. Lütfen daha sonra tekrar deneyin.',
        'assistant.placeholder': 'Sorunuzu buraya yazın...',
        'assistant.send': 'Gönder',
        'assistant.tooltip': 'AI Garsona Sor',
        'assistant.title': 'Gurme AI',
        'assistant.subtitle': 'Kozbeyli Konağı Asistanı',
        'assistant.prompt1': 'Ne yemeliyim?',
        'assistant.prompt2': 'Tatlı önerisi',
        'assistant.prompt3': 'Sıcak içecekler',
        'assistant.prompt4': 'Et yemekleri',

        // Sidebar
        'sidebar.adminPanel': 'Yönetim Paneli',
        'sidebar.location': 'Konum',
        'sidebar.call': 'Ara',
        'sidebar.rateUs': 'Değerlendir',

        // Dashboard - Sidebar Nav
        'dash.home': 'Ana Sayfa',
        'dash.menuManagement': 'Menü Yönetimi',
        'dash.events': 'Etkinlik Tanıtımı',
        'dash.analytics': 'Analitik',
        'dash.reviews': 'Yorumlar',
        'dash.translations': 'Çeviri',
        'dash.settings': 'Ayarlar',
        'dash.closeSidebar': 'Menü kapat',
        'dash.language': 'Dil',
        'dash.logout': 'Çıkış Yap',
        'dash.dbActive': 'Veritabanı: Aktif',
        'dash.dbDemo': 'Veritabanı: Demo',
        'dash.backToMenu': 'Menüye Dön',

        // Dashboard - Reviews Page
        'dash.reviews.title': 'Değerlendirmeler',
        'dash.reviews.subtitle': 'Müşteri yorumları ve puanları.',
        'dash.reviews.avgRating': 'Ortalama Puan',
        'dash.reviews.totalReviews': 'Toplam Yorum',
        'dash.reviews.recent': 'Son Yorumlar',
        'dash.reviews.loading': 'Yükleniyor...',
        'dash.reviews.empty': 'Henüz hiç yorum yapılmamış.',
        'dash.reviews.guest': 'Misafir',
        'dash.reviews.loadError': 'Yorumlar yüklenemedi.',

        // Dashboard - HomePage
        'dash.welcome': 'Hoş Geldiniz!',
        'dash.welcomeDesc': 'Dijital menü yönetim paneline hoş geldiniz. Aşağıdaki hızlı erişim kartlarını kullanarak işlemlerinize başlayabilirsiniz.',
        'dash.quickAccess': 'Hızlı Erişim',
        'dash.support': 'Destek',
        'dash.supportDesc': 'Herhangi bir sorunuz veya sorununuz mu var? Destek ekibimizle iletişime geçin.',
        'dash.action.categories': 'Kategoriler & Ürünler',
        'dash.action.categoriesDesc': 'Menü kategorilerinizi ve ürünlerinizi yönetin',
        'dash.action.display': 'Görüntüleme Tercihleri',
        'dash.action.displayDesc': 'Menünüzün görünümünü özelleştirin',
        'dash.action.translation': 'Çeviri Paneli',
        'dash.action.translationDesc': 'Menünüzü farklı dillere çevirin',
        'dash.action.settingsDesc': 'Restoran ve hesap ayarlarınızı düzenleyin',
        'dash.action.demo': 'Demo Menü',
        'dash.action.demoDesc': 'Menünüzün müşteri görünümünü önizleyin',
        'dash.action.tutorial': 'Hızlı Eğitim',
        'dash.action.tutorialDesc': 'Platform kullanım rehberini inceleyin',

        // Dashboard - MenuManagement
        'dash.menu.title': 'Menü Yönetimi',
        'dash.menu.tabProducts': 'Kategoriler & Ürünler',
        'dash.menu.tabRecommendations': 'Öneriler',
        'dash.menu.tabDisplay': 'Görüntüleme Tercihleri',
        'dash.menu.allCategories': 'Tüm Kategoriler',
        'dash.menu.addCategory': 'Kategori Ekle',
        'dash.menu.searchProduct': 'Ürün ara...',
        'dash.menu.addProduct': 'Ürün Ekle',
        'dash.menu.thProduct': 'Ürün',
        'dash.menu.thPrice': 'Fiyat',
        'dash.menu.thStatus': 'Durum',
        'dash.menu.thActions': 'İşlemler',
        'dash.menu.active': 'Aktif',
        'dash.menu.inactive': 'Pasif',
        'dash.menu.noProducts': 'Bu kategoride ürün bulunamadı.',
        'dash.menu.totalProducts': 'Toplam {count} ürün gösteriliyor',
        'dash.menu.editProduct': 'Ürün Düzenle',
        'dash.menu.productName': 'Ürün Adı',
        'dash.menu.price': 'Fiyat',
        'dash.menu.currency': 'Para Birimi',
        'dash.menu.description': 'Açıklama',
        'dash.menu.productImage': 'Ürün Görseli',
        'dash.menu.imageUpload': 'Görsel yüklemek için tıklayın veya sürükleyin',
        'dash.menu.imageFormats': 'PNG, JPG, WEBP (max 2MB)',
        'dash.menu.calories': 'Kalori (kcal)',
        'dash.menu.grams': 'Gram (g)',
        'dash.menu.servingTime': 'Servis Süresi (dk)',
        'dash.menu.dietary': 'Diyet Kısıtlamaları',
        'dash.menu.allergens': 'Alerjenler',
        'dash.menu.productStatus': 'Ürün Durumu',
        'dash.menu.showHide': 'Ürünü menüde göster/gizle',
        'dash.menu.cancel': 'İptal',
        'dash.menu.save': 'Kaydet',
        'dash.menu.saved': 'Ürün kaydedildi',
        'dash.menu.edit': 'Düzenle',
        'dash.menu.delete': 'Sil',
        'dash.menu.recommended': 'Önerilen Ürünler',
        'dash.menu.recommendedDesc': 'Müşterilere önerilecek özel ürünleri seçin',
        'dash.menu.addRecommendation': 'Öneri Ekle',
        'dash.menu.restaurantInfo': 'Restoran Bilgileri',
        'dash.menu.restaurantName': 'Restoran Adı',
        'dash.menu.logo': 'Logo',
        'dash.menu.logoUpload': 'Logo yükleyin',
        'dash.menu.videoUrl': 'Tanıtım Videosu URL',
        'dash.menu.themeSettings': 'Tema Ayarları',
        'dash.menu.colorTheme': 'Renk Teması',
        'dash.menu.categoryView': 'Kategori Görünümü',
        'dash.menu.saveChanges': 'Değişiklikleri Kaydet',
        'dash.menu.categorySoon': 'Kategori ekleme yakında aktif olacak',
        'dash.menu.productSoon': 'Ürün ekleme yakında aktif olacak',
        'dash.menu.deleteSoon': 'Silme işlemi yakında aktif olacak',
        'dash.menu.recommendSoon': 'Öneri ekleme yakında aktif olacak',
        'dash.menu.notes': 'Açıklamalar / Notlar',
        'dash.menu.notesDesc': 'Ürün altında gösterilecek ek bilgiler ekleyin. Birden fazla eklenebilir.',
        'dash.menu.notePlaceholder': 'Açıklama yazın ve Enter\'a basın...',
        'dash.menu.removeNote': 'Notu kaldır',

        // Dashboard - AI Recommendations
        'dash.rec.title': 'AI Ürün Önerileri',
        'dash.rec.desc': 'Yapay zeka ile ürünleriniz için çapraz satış önerileri oluşturun. Her ürün için en uygun eşleşmeleri otomatik belirleyin.',
        'dash.rec.aiActive': 'AI Aktif ({provider})',
        'dash.rec.aiInactive': 'AI Bağlantısı Yok',
        'dash.rec.noAI': 'AI sağlayıcısı yapılandırılmamış. .env dosyasına API anahtarı ekleyin.',
        'dash.rec.paired': 'Eşleşen Ürün',
        'dash.rec.unpaired': 'Eşleşmemiş',
        'dash.rec.generateAll': 'Tümünü Oluştur',
        'dash.rec.generating': 'Oluşturuluyor...',
        'dash.rec.generate': 'AI ile Oluştur',
        'dash.rec.regenerate': 'Yeniden Oluştur',
        'dash.rec.generated': '"{name}" için öneriler oluşturuldu!',
        'dash.rec.allDone': '{success} ürün için öneriler oluşturuldu, {failed} başarısız.',
        'dash.rec.removed': 'Öneriler kaldırıldı',
        'dash.rec.error': 'Öneriler oluşturulamadı',
        'dash.rec.noResults': 'AI öneri üretemedi, tekrar deneyin',
        'dash.rec.pairings': 'Eşleşmeler',
        'dash.rec.recommendation': 'öneri',
        'dash.rec.noPairings': 'Henüz öneri yok',

        // Dashboard - AnalyticsPage
        'dash.analytics.title': 'Analitik',
        'dash.analytics.totalClicks': 'Toplam Tıklama',
        'dash.analytics.totalViews': 'Toplam Görüntüleme',
        'dash.analytics.totalSessions': 'Toplam Oturum',
        'dash.analytics.qrScans': 'QR Tarama',
        'dash.analytics.last7': 'Son 7 gün',
        'dash.analytics.last30': 'Son 30 gün',
        'dash.analytics.last90': 'Son 90 gün',
        'dash.analytics.allTime': 'Tüm zamanlar',
        'dash.analytics.topClicked': 'En Çok Tıklanan Ürünler',
        'dash.analytics.topViewed': 'En Çok Görüntülenen Kategoriler',
        'dash.analytics.leastViewed': 'En Az Görüntülenen Ürünler',
        'dash.analytics.views': 'görüntüleme',
        'dash.analytics.avgTime': 'Ortalama Menü Süresi',
        'dash.analytics.deviceDist': 'Cihaz Dağılımı',
        'dash.analytics.trafficSources': 'Trafik Kaynakları',
        'dash.analytics.peakHours': 'Yoğun Saatler',
        'dash.analytics.qrTable': 'QR Kod (Masa)',
        'dash.analytics.qrEntrance': 'QR Kod (Giriş)',
        'dash.analytics.directLink': 'Doğrudan Link',
        'dash.analytics.socialMedia': 'Sosyal Medya',

        // Dashboard - EventsPage
        'dash.events.title': 'Etkinlik Tanıtımı',
        'dash.events.create': 'Etkinlik Oluştur',
        'dash.events.all': 'Tümü',
        'dash.events.upcoming': 'Yaklaşan',
        'dash.events.past': 'Geçmiş',
        'dash.events.notFound': 'Etkinlik bulunamadı.',
        'dash.events.people': 'kişi',
        'dash.events.editSoon': 'Düzenleme yakında aktif olacak',
        'dash.events.deleteSoon': 'Silme yakında aktif olacak',
        'dash.events.image': 'Etkinlik Görseli',
        'dash.events.uploadMedia': 'Görsel veya video yükleyin',
        'dash.events.name': 'Etkinlik Adı',
        'dash.events.namePlaceholder': 'Etkinlik adını girin',
        'dash.events.date': 'Tarih',
        'dash.events.time': 'Saat',
        'dash.events.location': 'Konum',
        'dash.events.locationPlaceholder': 'Etkinlik konumu',
        'dash.events.category': 'Kategori',
        'dash.events.capacity': 'Kapasite',
        'dash.events.capacityPlaceholder': 'Maksimum katılımcı sayısı',
        'dash.events.description': 'Açıklama',
        'dash.events.descPlaceholder': 'Etkinlik detaylarını yazın',
        'dash.events.phone': 'İletişim Telefon',
        'dash.events.email': 'İletişim E-posta',
        'dash.events.price': 'Fiyat (₺)',
        'dash.events.priceFree': '0 = Ücretsiz',
        'dash.events.paymentMethod': 'Ödeme Yöntemi',
        'dash.events.payAtDoor': 'Kapıda Ödeme',
        'dash.events.payOnline': 'Online Ödeme',
        'dash.events.free': 'Ücretsiz',
        'dash.events.cancelBtn': 'İptal',
        'dash.events.createBtn': 'Oluştur',
        'dash.events.created': 'Etkinlik oluşturuldu',
        'dash.events.close': 'Kapat',
        'dash.events.catMusic': 'Müzik',
        'dash.events.catWorkshop': 'Atölye',
        'dash.events.catTasting': 'Tadım',
        'dash.events.catFestival': 'Festival',
        'dash.events.catSpecial': 'Özel Gece',

        // Dashboard - SettingsPage
        'dash.settings.title': 'Ayarlar',
        'dash.settings.profile': 'Profil',
        'dash.settings.password': 'Şifre',
        'dash.settings.restaurant': 'Restoran Bilgileri',
        'dash.settings.guest': 'Misafir Bilgileri',
        'dash.settings.qrCode': 'QR Kod Oluşturucu',
        'dash.settings.aiChat': 'AI Sohbet Botu',
        'dash.settings.pdfMenu': 'PDF Menü',
        'dash.settings.languageSetting': 'Dil',
        'dash.settings.billing': 'Plan & Faturalandırma',
        'dash.settings.profileInfo': 'Profil Bilgileri',
        'dash.settings.changePhoto': 'Fotoğraf Değiştir',
        'dash.settings.firstName': 'Ad',
        'dash.settings.lastName': 'Soyad',
        'dash.settings.email': 'E-posta',
        'dash.settings.phone': 'Telefon',
        'dash.settings.save': 'Kaydet',
        'dash.settings.saved': 'Kaydedildi',
        'dash.settings.changePassword': 'Şifre Değiştir',
        'dash.settings.currentPassword': 'Mevcut Şifre',
        'dash.settings.newPassword': 'Yeni Şifre',
        'dash.settings.confirmPassword': 'Yeni Şifre (Tekrar)',
        'dash.settings.passwordHint': 'Şifreniz en az 8 karakter, büyük harf, küçük harf ve rakam içermelidir.',
        'dash.settings.restaurantName': 'Restoran Adı',
        'dash.settings.restaurantDesc': 'Açıklama',
        'dash.settings.address': 'Adres',
        'dash.settings.city': 'Şehir',
        'dash.settings.country': 'Ülke',
        'dash.settings.logoLabel': 'Logo',
        'dash.settings.logoUpload': 'Logo yükleyin',
        'dash.settings.guestCollection': 'Misafir Bilgi Toplama',
        'dash.settings.guestCollectionDesc': 'Menüye erişmeden önce müşterilerden hangi bilgilerin toplanacağını ayarlayın.',
        'dash.settings.required': 'Zorunlu',
        'dash.settings.fullName': 'Ad Soyad',
        'dash.settings.tableNumber': 'Masa Numarası',
        'dash.settings.qrTitle': 'QR Kod Oluşturucu',
        'dash.settings.qrDesc': 'Restoranınız için özel QR kodlar oluşturun ve indirin.',
        'dash.settings.fgColor': 'Ön Plan Rengi',
        'dash.settings.bgColor': 'Arka Plan Rengi',
        'dash.settings.downloadPng': 'PNG İndir',
        'dash.settings.downloadSvg': 'SVG İndir',
        'dash.settings.pngDownloaded': 'PNG indirildi!',
        'dash.settings.svgDownloaded': 'SVG indirildi!',
        'dash.settings.copied': 'Kopyalandı',
        'dash.settings.aiChatSettings': 'AI Sohbet Botu Ayarları',
        'dash.settings.aiChatDesc': 'Müşterileriniz için AI destekli sohbet botunu yapılandırın.',
        'dash.settings.chatBot': 'Sohbet Botu',
        'dash.settings.chatBotDesc': 'Menüde AI sohbet botunu etkinleştirin',
        'dash.settings.welcomeMessage': 'Karşılama Mesajı',
        'dash.settings.botCharacter': 'Bot Karakteri',
        'dash.settings.aiModel': 'AI Modeli',
        'dash.settings.pdfTitle': 'PDF Menü İndirme',
        'dash.settings.pdfDesc': 'Menünüzün PDF versiyonunu oluşturun ve indirin.',
        'dash.settings.pdfDownload': 'İndir',
        'dash.settings.pdfRegenerate': 'PDF Yeniden Oluştur',
        'dash.settings.panelLanguage': 'Panel Dili',
        'dash.settings.menuDefaultLang': 'Menü Varsayılan Dili',
        'dash.settings.premiumPlan': 'Premium Plan',
        'dash.settings.monthlyBilling': 'Aylık faturalandırma',
        'dash.settings.planFeatures': 'Plan Özellikleri',
        'dash.settings.changePlan': 'Planı Değiştir',
        'dash.settings.paymentMethod': 'Ödeme Yöntemi',
        'dash.settings.feat.unlimitedProducts': 'Sınırsız ürün ekleme',
        'dash.settings.feat.qrGenerator': 'QR Kod oluşturucu',
        'dash.settings.feat.aiChatBot': 'AI Sohbet Botu',
        'dash.settings.feat.analytics': 'Analitik dashboard',
        'dash.settings.feat.multiLang': 'Çoklu dil desteği',
        'dash.settings.feat.prioritySupport': 'Öncelikli destek',

        // Dashboard - TranslationsPage
        'dash.trans.title': 'Çeviri Yönetimi',
        'dash.trans.autoTranslate': 'Otomatik Çevir',
        'dash.trans.autoSoon': 'Otomatik çeviri yakında aktif olacak',
        'dash.trans.searchPlaceholder': 'Ürün veya kategori ara...',
        'dash.trans.type': 'Tür',
        'dash.trans.original': 'Orijinal (Türkçe)',
        'dash.trans.translation': 'Çeviri',
        'dash.trans.status': 'Durum',
        'dash.trans.category': 'Kategori',
        'dash.trans.product': 'Ürün',
        'dash.trans.completed': 'Tamamlandı',
        'dash.trans.pending': 'Bekliyor',
        'dash.trans.noTranslation': 'Çeviri yok',
        'dash.trans.enterTranslation': 'Çeviri girin...',
        'dash.trans.noResults': 'Sonuç bulunamadı.',
        'dash.trans.progress': '%{percent} tamamlandı',

        // Dashboard - EventsPage Sample Data
        'dash.events.sample.liveMusic': 'Canlı Müzik Gecesi',
        'dash.events.sample.chefWorkshop': 'Şef ile Yemek Atölyesi',
        'dash.events.sample.tastingNight': 'Tadım Gecesi - İtalyan Şarapları',
        'dash.events.sample.breakfastFest': 'Kahvaltı Festivali',
        'dash.events.sample.mainHall': 'Ana Salon',
        'dash.events.sample.kitchenStudio': 'Mutfak Stüdyo',
        'dash.events.sample.wineCellar': 'Şarap Mahzeni',
        'dash.events.sample.garden': 'Bahçe',

        // Dashboard - SettingsPage extras
        'dash.settings.welcomeDefault': 'Merhaba! Size nasıl yardımcı olabilirim?',
        'dash.settings.botCharacterDefault': 'Kozbeyli Konağı\'nın yardımcı asistanı olarak, menü hakkında bilgi verin. Nazik ve profesyonel olun.',
        'dash.settings.pdfFileName': 'Kozbeyli Konağı Menü.pdf',
        'dash.settings.pdfLastUpdate': 'Son güncelleme: 20 Ocak 2025',

        // Dashboard - MenuManagement Dietary Tags
        'dash.menu.diet.vegan': 'Vegan',
        'dash.menu.diet.vegetarian': 'Vejeteryan',
        'dash.menu.diet.glutenFree': 'Glutensiz',
        'dash.menu.diet.lactoseFree': 'Laktoz İçermez',
        'dash.menu.diet.organic': 'Organik',
        'dash.menu.diet.halal': 'Helal',
        'dash.menu.allergen.gluten': 'Gluten',
        'dash.menu.allergen.dairy': 'Süt',
        'dash.menu.allergen.egg': 'Yumurta',
        'dash.menu.allergen.peanut': 'Fıstık',
        'dash.menu.allergen.soy': 'Soya',
        'dash.menu.allergen.fish': 'Balık',
        'dash.menu.allergen.shellfish': 'Kabuklu Deniz',
        'dash.menu.allergen.celery': 'Kereviz',
        'dash.menu.allergen.mustard': 'Hardal',
        'dash.menu.allergen.sesame': 'Susam',
        'dash.menu.listView': 'Liste',

        // QRCodeEditor
        'qr.themeApplied': '"{name}" teması uygulandı',
        'qr.enterNameFirst': 'Lütfen önce restoran adı girin',
        'qr.aiGenerated': 'AI önerileri oluşturuldu!',
        'qr.aiFailed': 'Öneriler oluşturulamadı',
        'qr.downloaded': 'Yüksek çözünürlüklü QR indirildi',
        'qr.quickPresets': 'Hızlı Şablonlar',
        'qr.website': 'Website',
        'qr.wifi': 'WiFi',
        'qr.destinationUrl': 'Hedef URL',
        'qr.ssid': 'SSID',
        'qr.password': 'Şifre',
        'qr.hiddenNetwork': 'Gizli Ağ',
        'qr.title': 'Başlık',
        'qr.subtitle': 'Alt Başlık',
        'qr.frameText': 'Çerçeve Yazısı',
        'qr.aiTaglineGenerator': 'AI Slogan Üretici',
        'qr.vibeAtmosphere': 'Atmosfer / Tarz',
        'qr.generating': 'Oluşturuluyor...',
        'qr.generateTaglines': 'Slogan Üret',
        'qr.appearance': 'Görünüm',
        'qr.foreground': 'Ön Plan',
        'qr.background': 'Arka Plan',
        'qr.useGradient': 'Gradyan Kullan',
        'qr.gradientStart': 'Gradyan Başlangıç',
        'qr.gradientEnd': 'Gradyan Bitiş',
        'qr.branding': 'Marka',
        'qr.uploadLogo': 'Logo Yükle',
        'qr.structure': 'Yapı (Taş Otel Görünümü)',
        'qr.contrast': 'Kontrast',
        'qr.poor': 'Zayıf',
        'qr.good': 'İyi',
        'qr.maxDistance': 'Maks Mesafe',
        'qr.printSize': 'Baskı Boyutu (cm)',
        'qr.downloadHighRes': 'Yüksek Çözünürlük İndir',
        'qr.showWoodenBase': 'Ahşap Tabanı Göster',

        // General
        'back': 'Geri',
        'search': 'Ara...',
        'loading': 'Yükleniyor...',
        'menu': 'Menü',
    },
    en: {
        // Common
        'close': 'Close',
        'nav.back': 'Back',

        // Cookie Consent
        'cookie.text': 'This site uses cookies to improve your experience. By continuing, you accept our cookie policy.',
        'cookie.accept': 'Accept',

        // VideoLanding
        'landing.title': 'Discover Taste',
        'landing.subtitle': "The finest flavors and unique presentations of the Aegean await you.",
        'landing.cta': 'View Menu',
        'landing.brandName': 'Kozbeyli Konağı',
        'landing.brandSub': 'Stone Hotel',
        'landing.switchLang': 'Türkçe',

        // CategoryGrid
        'menu.welcome': 'Welcome',
        'menu.restaurant': 'Kozbeyli Konağı',
        'menu.search': 'What would you like to eat?',
        'menu.categories': 'Categories',
        'menu.poweredBy': 'Kozbeyli Konağı',

        // ProductModal
        'product.addToOrder': 'Add to Order',
        'product.addedToOrder': 'Added to order!',
        'product.shared': 'Copied!',
        'product.share': 'Share',
        'product.outOfStock': 'Out of Stock',
        'product.notFound': 'Product not found.',
        'product.pairingTitle': 'Gourmet Pairing',
        'product.suggestions': 'Suggestions',
        'product.why': 'Why?',
        'product.notes': 'Notes',
        'product.category': 'Category',
        'product.explore': 'Explore',
        'product.showMore': 'Show More',
        'product.showLess': 'Show Less',
        'product.info': 'Info',

        // Review
        'review.title': 'Rate Us',
        'review.rateExperience': 'Rate your experience',
        'review.nameLabel': 'Name (Optional)',
        'review.namePlaceholder': 'Your name...',
        'review.commentLabel': 'Your Review',
        'review.commentPlaceholder': 'Share your thoughts...',
        'review.submit': 'Submit',
        'review.thankYou': 'Thank You!',
        'review.thankYouMessage': 'Your feedback is very valuable to us.',
        'review.ratingRequired': 'Please give a rating.',
        'review.error': 'An error occurred.',
        'review.rating5': 'Amazing!',
        'review.rating4': 'Very Good',
        'review.rating3': 'Average',
        'review.rating2': 'Poor',
        'review.rating1': 'Very Poor',

        // AI Assistant
        'assistant.welcome': 'Hello! I am the AI assistant of Kozbeyli Konagi. How can I help you with our menu?',
        'assistant.error': 'Sorry, I cannot respond right now. Please try again later.',
        'assistant.placeholder': 'Type your question here...',
        'assistant.send': 'Send',
        'assistant.tooltip': 'Ask AI Waiter',
        'assistant.title': 'Gourmet AI',
        'assistant.subtitle': 'Kozbeyli Konagi Assistant',
        'assistant.prompt1': 'What should I eat?',
        'assistant.prompt2': 'Dessert suggestion',
        'assistant.prompt3': 'Hot drinks',
        'assistant.prompt4': 'Meat dishes',

        // Sidebar
        'sidebar.adminPanel': 'Admin Panel',
        'sidebar.location': 'Location',
        'sidebar.call': 'Call',
        'sidebar.rateUs': 'Rate Us',

        // Dashboard - Sidebar Nav
        'dash.home': 'Home',
        'dash.menuManagement': 'Menu Management',
        'dash.events': 'Events',
        'dash.analytics': 'Analytics',
        'dash.reviews': 'Reviews',
        'dash.translations': 'Translations',
        'dash.settings': 'Settings',
        'dash.closeSidebar': 'Close menu',
        'dash.language': 'Language',
        'dash.logout': 'Logout',
        'dash.dbActive': 'Database: Active',
        'dash.dbDemo': 'Database: Demo',
        'dash.backToMenu': 'Back to Menu',

        // Dashboard - Reviews Page
        'dash.reviews.title': 'Reviews',
        'dash.reviews.subtitle': 'Customer reviews and ratings.',
        'dash.reviews.avgRating': 'Average Rating',
        'dash.reviews.totalReviews': 'Total Reviews',
        'dash.reviews.recent': 'Recent Reviews',
        'dash.reviews.loading': 'Loading...',
        'dash.reviews.empty': 'No reviews yet.',
        'dash.reviews.guest': 'Guest',
        'dash.reviews.loadError': 'Could not load reviews.',

        // Dashboard - HomePage
        'dash.welcome': 'Welcome!',
        'dash.welcomeDesc': 'Welcome to the digital menu management panel. Use the quick access cards below to get started.',
        'dash.quickAccess': 'Quick Access',
        'dash.support': 'Support',
        'dash.supportDesc': 'Have a question or issue? Contact our support team.',
        'dash.action.categories': 'Categories & Products',
        'dash.action.categoriesDesc': 'Manage your menu categories and products',
        'dash.action.display': 'Display Preferences',
        'dash.action.displayDesc': 'Customize how your menu looks',
        'dash.action.translation': 'Translation Panel',
        'dash.action.translationDesc': 'Translate your menu into different languages',
        'dash.action.settingsDesc': 'Manage restaurant and account settings',
        'dash.action.demo': 'Demo Menu',
        'dash.action.demoDesc': 'Preview your menu as customers see it',
        'dash.action.tutorial': 'Quick Tutorial',
        'dash.action.tutorialDesc': 'View the platform usage guide',

        // Dashboard - MenuManagement
        'dash.menu.title': 'Menu Management',
        'dash.menu.tabProducts': 'Categories & Products',
        'dash.menu.tabRecommendations': 'Recommendations',
        'dash.menu.tabDisplay': 'Display Preferences',
        'dash.menu.allCategories': 'All Categories',
        'dash.menu.addCategory': 'Add Category',
        'dash.menu.searchProduct': 'Search product...',
        'dash.menu.addProduct': 'Add Product',
        'dash.menu.thProduct': 'Product',
        'dash.menu.thPrice': 'Price',
        'dash.menu.thStatus': 'Status',
        'dash.menu.thActions': 'Actions',
        'dash.menu.active': 'Active',
        'dash.menu.inactive': 'Inactive',
        'dash.menu.noProducts': 'No products found in this category.',
        'dash.menu.totalProducts': 'Showing {count} products total',
        'dash.menu.editProduct': 'Edit Product',
        'dash.menu.productName': 'Product Name',
        'dash.menu.price': 'Price',
        'dash.menu.currency': 'Currency',
        'dash.menu.description': 'Description',
        'dash.menu.productImage': 'Product Image',
        'dash.menu.imageUpload': 'Click or drag to upload image',
        'dash.menu.imageFormats': 'PNG, JPG, WEBP (max 2MB)',
        'dash.menu.calories': 'Calories (kcal)',
        'dash.menu.grams': 'Weight (g)',
        'dash.menu.servingTime': 'Serving Time (min)',
        'dash.menu.dietary': 'Dietary Restrictions',
        'dash.menu.allergens': 'Allergens',
        'dash.menu.productStatus': 'Product Status',
        'dash.menu.showHide': 'Show/hide product on menu',
        'dash.menu.cancel': 'Cancel',
        'dash.menu.save': 'Save',
        'dash.menu.saved': 'Product saved',
        'dash.menu.edit': 'Edit',
        'dash.menu.delete': 'Delete',
        'dash.menu.recommended': 'Recommended Products',
        'dash.menu.recommendedDesc': 'Select special products to recommend to customers',
        'dash.menu.addRecommendation': 'Add Recommendation',
        'dash.menu.restaurantInfo': 'Restaurant Info',
        'dash.menu.restaurantName': 'Restaurant Name',
        'dash.menu.logo': 'Logo',
        'dash.menu.logoUpload': 'Upload logo',
        'dash.menu.videoUrl': 'Promo Video URL',
        'dash.menu.themeSettings': 'Theme Settings',
        'dash.menu.colorTheme': 'Color Theme',
        'dash.menu.categoryView': 'Category View',
        'dash.menu.saveChanges': 'Save Changes',
        'dash.menu.categorySoon': 'Add category coming soon',
        'dash.menu.productSoon': 'Add product coming soon',
        'dash.menu.deleteSoon': 'Delete coming soon',
        'dash.menu.recommendSoon': 'Add recommendation coming soon',
        'dash.menu.notes': 'Notes / Explanations',
        'dash.menu.notesDesc': 'Add extra information to show below the product. Multiple notes can be added.',
        'dash.menu.notePlaceholder': 'Type a note and press Enter...',
        'dash.menu.removeNote': 'Remove note',

        // Dashboard - AI Recommendations
        'dash.rec.title': 'AI Product Recommendations',
        'dash.rec.desc': 'Generate cross-sell recommendations for your products using AI. Automatically find the best pairings for each item.',
        'dash.rec.aiActive': 'AI Active ({provider})',
        'dash.rec.aiInactive': 'No AI Connection',
        'dash.rec.noAI': 'No AI provider configured. Add an API key to .env file.',
        'dash.rec.paired': 'Paired Products',
        'dash.rec.unpaired': 'Unpaired',
        'dash.rec.generateAll': 'Generate All',
        'dash.rec.generating': 'Generating...',
        'dash.rec.generate': 'Generate with AI',
        'dash.rec.regenerate': 'Regenerate',
        'dash.rec.generated': 'Recommendations generated for "{name}"!',
        'dash.rec.allDone': 'Generated for {success} products, {failed} failed.',
        'dash.rec.removed': 'Recommendations removed',
        'dash.rec.error': 'Could not generate recommendations',
        'dash.rec.noResults': 'AI could not produce recommendations, try again',
        'dash.rec.pairings': 'Pairings',
        'dash.rec.recommendation': 'recommendation(s)',
        'dash.rec.noPairings': 'No pairings yet',

        // Dashboard - AnalyticsPage
        'dash.analytics.title': 'Analytics',
        'dash.analytics.totalClicks': 'Total Clicks',
        'dash.analytics.totalViews': 'Total Views',
        'dash.analytics.totalSessions': 'Total Sessions',
        'dash.analytics.qrScans': 'QR Scans',
        'dash.analytics.last7': 'Last 7 days',
        'dash.analytics.last30': 'Last 30 days',
        'dash.analytics.last90': 'Last 90 days',
        'dash.analytics.allTime': 'All time',
        'dash.analytics.topClicked': 'Most Clicked Products',
        'dash.analytics.topViewed': 'Most Viewed Categories',
        'dash.analytics.leastViewed': 'Least Viewed Products',
        'dash.analytics.views': 'views',
        'dash.analytics.avgTime': 'Average Menu Time',
        'dash.analytics.deviceDist': 'Device Distribution',
        'dash.analytics.trafficSources': 'Traffic Sources',
        'dash.analytics.peakHours': 'Peak Hours',
        'dash.analytics.qrTable': 'QR Code (Table)',
        'dash.analytics.qrEntrance': 'QR Code (Entrance)',
        'dash.analytics.directLink': 'Direct Link',
        'dash.analytics.socialMedia': 'Social Media',

        // Dashboard - EventsPage
        'dash.events.title': 'Event Promotion',
        'dash.events.create': 'Create Event',
        'dash.events.all': 'All',
        'dash.events.upcoming': 'Upcoming',
        'dash.events.past': 'Past',
        'dash.events.notFound': 'No events found.',
        'dash.events.people': 'people',
        'dash.events.editSoon': 'Edit coming soon',
        'dash.events.deleteSoon': 'Delete coming soon',
        'dash.events.image': 'Event Image',
        'dash.events.uploadMedia': 'Upload image or video',
        'dash.events.name': 'Event Name',
        'dash.events.namePlaceholder': 'Enter event name',
        'dash.events.date': 'Date',
        'dash.events.time': 'Time',
        'dash.events.location': 'Location',
        'dash.events.locationPlaceholder': 'Event location',
        'dash.events.category': 'Category',
        'dash.events.capacity': 'Capacity',
        'dash.events.capacityPlaceholder': 'Maximum attendees',
        'dash.events.description': 'Description',
        'dash.events.descPlaceholder': 'Write event details',
        'dash.events.phone': 'Contact Phone',
        'dash.events.email': 'Contact Email',
        'dash.events.price': 'Price (₺)',
        'dash.events.priceFree': '0 = Free',
        'dash.events.paymentMethod': 'Payment Method',
        'dash.events.payAtDoor': 'Pay at Door',
        'dash.events.payOnline': 'Online Payment',
        'dash.events.free': 'Free',
        'dash.events.cancelBtn': 'Cancel',
        'dash.events.createBtn': 'Create',
        'dash.events.created': 'Event created',
        'dash.events.close': 'Close',
        'dash.events.catMusic': 'Music',
        'dash.events.catWorkshop': 'Workshop',
        'dash.events.catTasting': 'Tasting',
        'dash.events.catFestival': 'Festival',
        'dash.events.catSpecial': 'Special Night',

        // Dashboard - SettingsPage
        'dash.settings.title': 'Settings',
        'dash.settings.profile': 'Profile',
        'dash.settings.password': 'Password',
        'dash.settings.restaurant': 'Restaurant Info',
        'dash.settings.guest': 'Guest Info',
        'dash.settings.qrCode': 'QR Code Generator',
        'dash.settings.aiChat': 'AI Chat Bot',
        'dash.settings.pdfMenu': 'PDF Menu',
        'dash.settings.languageSetting': 'Language',
        'dash.settings.billing': 'Plan & Billing',
        'dash.settings.profileInfo': 'Profile Information',
        'dash.settings.changePhoto': 'Change Photo',
        'dash.settings.firstName': 'First Name',
        'dash.settings.lastName': 'Last Name',
        'dash.settings.email': 'Email',
        'dash.settings.phone': 'Phone',
        'dash.settings.save': 'Save',
        'dash.settings.saved': 'Saved',
        'dash.settings.changePassword': 'Change Password',
        'dash.settings.currentPassword': 'Current Password',
        'dash.settings.newPassword': 'New Password',
        'dash.settings.confirmPassword': 'Confirm New Password',
        'dash.settings.passwordHint': 'Password must be at least 8 characters with uppercase, lowercase and numbers.',
        'dash.settings.restaurantName': 'Restaurant Name',
        'dash.settings.restaurantDesc': 'Description',
        'dash.settings.address': 'Address',
        'dash.settings.city': 'City',
        'dash.settings.country': 'Country',
        'dash.settings.logoLabel': 'Logo',
        'dash.settings.logoUpload': 'Upload logo',
        'dash.settings.guestCollection': 'Guest Info Collection',
        'dash.settings.guestCollectionDesc': 'Set which information to collect from customers before menu access.',
        'dash.settings.required': 'Required',
        'dash.settings.fullName': 'Full Name',
        'dash.settings.tableNumber': 'Table Number',
        'dash.settings.qrTitle': 'QR Code Generator',
        'dash.settings.qrDesc': 'Create and download custom QR codes for your restaurant.',
        'dash.settings.fgColor': 'Foreground Color',
        'dash.settings.bgColor': 'Background Color',
        'dash.settings.downloadPng': 'Download PNG',
        'dash.settings.downloadSvg': 'Download SVG',
        'dash.settings.pngDownloaded': 'PNG downloaded!',
        'dash.settings.svgDownloaded': 'SVG downloaded!',
        'dash.settings.copied': 'Copied',
        'dash.settings.aiChatSettings': 'AI Chat Bot Settings',
        'dash.settings.aiChatDesc': 'Configure the AI-powered chat bot for your customers.',
        'dash.settings.chatBot': 'Chat Bot',
        'dash.settings.chatBotDesc': 'Enable AI chat bot on the menu',
        'dash.settings.welcomeMessage': 'Welcome Message',
        'dash.settings.botCharacter': 'Bot Character',
        'dash.settings.aiModel': 'AI Model',
        'dash.settings.pdfTitle': 'PDF Menu Download',
        'dash.settings.pdfDesc': 'Create and download the PDF version of your menu.',
        'dash.settings.pdfDownload': 'Download',
        'dash.settings.pdfRegenerate': 'Regenerate PDF',
        'dash.settings.panelLanguage': 'Panel Language',
        'dash.settings.menuDefaultLang': 'Menu Default Language',
        'dash.settings.premiumPlan': 'Premium Plan',
        'dash.settings.monthlyBilling': 'Monthly billing',
        'dash.settings.planFeatures': 'Plan Features',
        'dash.settings.changePlan': 'Change Plan',
        'dash.settings.paymentMethod': 'Payment Method',
        'dash.settings.feat.unlimitedProducts': 'Unlimited product additions',
        'dash.settings.feat.qrGenerator': 'QR Code generator',
        'dash.settings.feat.aiChatBot': 'AI Chat Bot',
        'dash.settings.feat.analytics': 'Analytics dashboard',
        'dash.settings.feat.multiLang': 'Multi-language support',
        'dash.settings.feat.prioritySupport': 'Priority support',

        // Dashboard - TranslationsPage
        'dash.trans.title': 'Translation Management',
        'dash.trans.autoTranslate': 'Auto Translate',
        'dash.trans.autoSoon': 'Auto translation coming soon',
        'dash.trans.searchPlaceholder': 'Search product or category...',
        'dash.trans.type': 'Type',
        'dash.trans.original': 'Original (Turkish)',
        'dash.trans.translation': 'Translation',
        'dash.trans.status': 'Status',
        'dash.trans.category': 'Category',
        'dash.trans.product': 'Product',
        'dash.trans.completed': 'Completed',
        'dash.trans.pending': 'Pending',
        'dash.trans.noTranslation': 'No translation',
        'dash.trans.enterTranslation': 'Enter translation...',
        'dash.trans.noResults': 'No results found.',
        'dash.trans.progress': '{percent}% completed',

        // Dashboard - EventsPage Sample Data
        'dash.events.sample.liveMusic': 'Live Music Night',
        'dash.events.sample.chefWorkshop': 'Cooking Workshop with Chef',
        'dash.events.sample.tastingNight': 'Tasting Night - Italian Wines',
        'dash.events.sample.breakfastFest': 'Breakfast Festival',
        'dash.events.sample.mainHall': 'Main Hall',
        'dash.events.sample.kitchenStudio': 'Kitchen Studio',
        'dash.events.sample.wineCellar': 'Wine Cellar',
        'dash.events.sample.garden': 'Garden',

        // Dashboard - SettingsPage extras
        'dash.settings.welcomeDefault': 'Hello! How can I help you?',
        'dash.settings.botCharacterDefault': 'As the helpful assistant of Kozbeyli Konagi, provide information about the menu. Be polite and professional.',
        'dash.settings.pdfFileName': 'Kozbeyli Konagi Menu.pdf',
        'dash.settings.pdfLastUpdate': 'Last update: January 20, 2025',

        // Dashboard - MenuManagement Dietary Tags
        'dash.menu.diet.vegan': 'Vegan',
        'dash.menu.diet.vegetarian': 'Vegetarian',
        'dash.menu.diet.glutenFree': 'Gluten-Free',
        'dash.menu.diet.lactoseFree': 'Lactose-Free',
        'dash.menu.diet.organic': 'Organic',
        'dash.menu.diet.halal': 'Halal',
        'dash.menu.allergen.gluten': 'Gluten',
        'dash.menu.allergen.dairy': 'Dairy',
        'dash.menu.allergen.egg': 'Egg',
        'dash.menu.allergen.peanut': 'Peanut',
        'dash.menu.allergen.soy': 'Soy',
        'dash.menu.allergen.fish': 'Fish',
        'dash.menu.allergen.shellfish': 'Shellfish',
        'dash.menu.allergen.celery': 'Celery',
        'dash.menu.allergen.mustard': 'Mustard',
        'dash.menu.allergen.sesame': 'Sesame',
        'dash.menu.listView': 'List',

        // QRCodeEditor
        'qr.themeApplied': '"{name}" theme applied',
        'qr.enterNameFirst': 'Please enter a restaurant name first',
        'qr.aiGenerated': 'AI suggestions generated!',
        'qr.aiFailed': 'Could not generate suggestions',
        'qr.downloaded': 'High-Res QR Downloaded',
        'qr.quickPresets': 'Quick Presets',
        'qr.website': 'Website',
        'qr.wifi': 'WiFi',
        'qr.destinationUrl': 'Destination URL',
        'qr.ssid': 'SSID',
        'qr.password': 'Password',
        'qr.hiddenNetwork': 'Hidden Network',
        'qr.title': 'Title',
        'qr.subtitle': 'Subtitle',
        'qr.frameText': 'Frame Text',
        'qr.aiTaglineGenerator': 'AI Tagline Generator',
        'qr.vibeAtmosphere': 'Vibe / Atmosphere',
        'qr.generating': 'Generating...',
        'qr.generateTaglines': 'Generate Taglines',
        'qr.appearance': 'Appearance',
        'qr.foreground': 'Foreground',
        'qr.background': 'Background',
        'qr.useGradient': 'Use Gradient',
        'qr.gradientStart': 'Gradient Start',
        'qr.gradientEnd': 'Gradient End',
        'qr.branding': 'Branding',
        'qr.uploadLogo': 'Upload Logo',
        'qr.structure': 'Structure (Stone Hotel Look)',
        'qr.contrast': 'Contrast',
        'qr.poor': 'Poor',
        'qr.good': 'Good',
        'qr.maxDistance': 'Max Distance',
        'qr.printSize': 'Print Size (cm)',
        'qr.downloadHighRes': 'Download High-Res',
        'qr.showWoodenBase': 'Show Wooden Base',

        // General
        'back': 'Back',
        'search': 'Search...',
        'loading': 'Loading...',
        'menu': 'Menu',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved as Language) || 'tr';
    });

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
